### ISSUE TITLE
Thêm những view còn lại

### ISSUE THREAD

**Issue by hoang3402** [Yersin-K18/BookLibrary#1]
- [x] Index 
- [x] #4
- [x] #5
- [x] #6
- [x] Error (404)
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17

**Comment by vule2303** [comment]
really?

**Comment by phu1110** [comment]
Ok

Vào 19:29, T.4, 4 Th1, 2023 vule2303 ***@***.***> đã viết:
