### ISSUE TITLE
Fix index-v2

### ISSUE THREAD

**Issue by hoang3402** [Yersin-K18/BookLibrary#44]
![image](https://user-images.githubusercontent.com/54090585/210578194-174145df-56a3-4df7-a481-4f5edb01233b.png)

**Comment by vule2303** [comment]
![image](https://user-images.githubusercontent.com/107258990/210699686-1f8a31f9-a579-4f81-a3b8-c99c089ebb4d.png)
thêm hết rồi mà ta

**Comment by vule2303** [comment]
không biết fix cái maps.google như nào cả hoàng ơi
