### ISSUE TITLE
Fix - Put the file in the wrong place

### ISSUE THREAD

**Issue by hoang3402** [Yersin-K18/BookLibrary#55]
![image](https://user-images.githubusercontent.com/54090585/211228558-64992b87-fa2f-4e46-a7f9-2bc72c50f78a.png)

nó k nên tồn tại :v

**Comment by TSanzz1229** [comment]
what, why ! t có push nó lên đâu, cái này t làm lâu r mà

**Comment by TSanzz1229** [comment]
xóa file.html hay xóa luôn view với controller luôn  á
