### ISSUE TITLE
particle product

### ISSUE THREAD

**Issue by hoang3402** [Yersin-K18/BookLibrary#62]
![image](https://user-images.githubusercontent.com/54090585/211439106-acfcc393-0855-4966-8d74-aa9f9d14639e.png)

Thay thành sửa cái "add to basket" sang tiếng việt nha

**Comment by vule2303** [comment]
là giờ làm gì

**Comment by vule2303** [comment]
hey bro, muốn lấy ra list best selling thì phải có database mục tổng số lượng xuất của các sách thì lấy ra được hoặc giờ chỉ cần hiện thị 7 cái đầu thì ok
