### ISSUE TITLE
Fix layout2 3

### ISSUE THREAD

**Issue by hoang3402** [Yersin-K18/BookLibrary#90]
![image](https://user-images.githubusercontent.com/54090585/216864058-2c4d581c-360a-430e-9c73-570b9551c2dd.png)
![image](https://user-images.githubusercontent.com/54090585/216864070-a1068bcc-b2c4-4fd2-bd58-d48ed2697145.png)

**Comment by vule2303** [comment]
ý là fix cái nào
fix cái css giỏ hàng à
