### ISSUE TITLE
Fix css for Products

### ISSUE THREAD

**Issue by hoang3402** [Yersin-K18/BookLibrary#95]
# Hiện tại khi đưa chuột vào thanh menu không hiện sub-menu
![image](https://user-images.githubusercontent.com/54090585/221357422-de9bd1b7-2025-4d9a-bb13-bbeee991e540.png)

**Comment by phu1110** [comment]
H t fix css hửm :))

Vào 20:13, T.5, 2 Th3, 2023 HoangDSR ***@***.***> đã viết:

**Comment by tdquang266** [comment]
if it ain't broke, don't fix it
